Server:
  Port: 8080

Redis:
  PubSubChannel: test_drone_channel
  Endpoints: localhost:6379
  Database: 0

Client:
  WindSimulation: true
  MovementServer:
    Port: 9000

Ballast:
  Enabled: false
  Size: "50M"